### ISSUE TITLE
[FEAT] 복약체크 홈 구현

### ISSUE THREAD

**Issue by kimdahee7** [Pill-Mate/Pill-Mate-Android#5]
## 💡 Issue
복약체크 홈 기능 구현
## 📌 To-do
- [ ] 상단 바 구성(알림/설정)
- [ ] 캘린더 및 날짜 선택 기능(주별 단위로 표시)
- [ ] 복약 진행률 표시 
- [ ] 복약 시간대별 RecyclerView 구현
