### ISSUE TITLE
[FEAT] 약국&병원 검색 기능 구현

### ISSUE THREAD

**Issue by BanDalKang** [Pill-Mate/Pill-Mate-Android#6]
## 💡 Issue
- [x] API를 사용한 검색 기능 구현 

## 📌 To-do
- [x] 약국&병원: BottomSheetFragment에서 검색
- [x] 유효성 검사: 약국 입력 필수, 병원은 선택 사항
- [x] 최근 검색어 저장 및 불러오기 기능 구현
